### ISSUE TITLE
Amazing!!!

### ISSUE THREAD

**Issue by virtualenv** [alecjacobson/skeleton-poser#1]
Congrats Alec!!!

Such an amazing job!
Question, is there a way to move the mesh around the scene ?
Suppose I want the mesh to lay down on the floor, I can make it a lay down position, but it is floating on the air, I would like to push it to the floor.
Or maybe even better, how could I add gravity to the scene ?

Thanks you!

**Comment by alecjacobson** [comment]
This little app can't do that. In the past I've done a satisfying trick to set the global y-offset to the minimum y value of the mesh so it's always touching the floor. That'd be easy to hack in here.

**Comment by virtualenv** [comment]
Dear Alec,

Thanks for your reply.
Let me tell you that your "little app" is the best example (with source code) that I found on the web!
